---

sudo: required

language: python
python:
  - "2.7"

services: docker

branches:
  only:
    - "master"

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

env:
  - ANSIBLE_VERSION=2.3.1.0
  - ANSIBLE_VERSION=2.2.3.0
  - ANSIBLE_VERSION=2.1.6.0
  - ANSIBLE_VERSION=2.0.2.0

script:
  - wget -O ${PWD}/run.sh https://raw.githubusercontent.com/pari-/docker-debian8-ansible/master/run.sh
  - chmod +x ${PWD}/run.sh
  - ${PWD}/run.sh
