---

- hosts: "all"
  vars:
    openntpd_config_options:
      listen_on:
        any:
          address: "*"
      servers:
        ptbtim1.ptb.de:
          address: "ptbtime1.ptb.de"
        ptbtime2.ptb.de:
          address: "ptbtime2.ptb.de"
        ptbtime3.ptb.de:
          address: "ptbtime3.ptb.de"
  roles:
    - role: "ansible-openntpd"
      tags:
        - "openntpd"
  post_tasks:
    - block:
        - include: "tests/test_ntpctl_show_all_data.yml"
      tags:
        - "tests"
