---

- name: fail unless we run on a supported distribution
  fail:
    msg: "Unfortunately, the 'openntpd'-role is not supported on {{ ansible_distribution_release }}! :-("
  when: ansible_distribution_release|lower not in openntpd_supported_distro_list

- name: install prerequisite packages
  apt:
    default_release: "{{ openntpd_pre_default_release }}"
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ openntpd_pre_package_list }}"
